#!/bin/bash
#
#
SRC=class

# some clean-up first
#  rm -f ${SRC}.dvi
#  rm -f feynmanpics.*

#  latex ${SRC}.tex 

#  DISPLAY= mf feynmanpics.mf 

#  latex ${SRC}.tex

  export TEXINPUTS=${TEXINPUTS}:$HOME/revtex4
  export BSTINPUTS=$TEXINPUTS

# temporary comment out bibtex;  restore it later!!
  latex ${SRC}.tex && bibtex ${SRC} &&
  latex ${SRC}.tex && latex ${SRC}.tex && dvips -o ${SRC}.ps ${SRC}.dvi

